{
  "hash": "da54dfd652aae02a0178a877e8d3fdb2",
  "result": {
    "engine": "jupyter",
    "markdown": "# 05 — Modelos Extendidos: ZIP y ZINB\n\n**Bayesian Workflow — Etapa: Model Expansion**\n\nEl análisis en `04_predictive_checks_base_models.ipynb` mostró que:\n- Poisson falla en dispersión **y** en ceros (p≈0 en ambas dimensiones)\n- Binomial Negativa captura la dispersión pero subestima los ceros (p=0.096)\n\nEl diagnóstico apunta a **inflación de ceros**: hay hembras que estructuralmente no atraen\nsatélites, y ese proceso generador es distinto del proceso de conteo.\n\n**Modelos a evaluar:**\n- **ZIP** (Zero-Inflated Poisson): mezcla π·δ₀ + (1-π)·Poisson(λ)\n- **ZINB** (Zero-Inflated Negative Binomial): mezcla π·δ₀ + (1-π)·NegBin(μ, φ)\n\nAmbos modelos tienen un componente logístico que decide si la observación es un\n\"cero estructural\" (la hembra definitivamente no tiene satélites) o si viene del\nproceso de conteo normal.\n\n## Prerequisito\nEjecutar primero `03_inferencia_bayesiana.ipynb` (modelos base) y este notebook\nen orden (ajusta ZIP y ZINB si los `.nc` no existen en `outputs/`).\n\n::: {#1 .cell execution_count=1}\n``` {.python .cell-code}\nimport numpy as np\nimport pandas as pd\nimport matplotlib.pyplot as plt\nimport seaborn as sns\nimport arviz as az\nimport cmdstanpy\nimport warnings\n\nwarnings.filterwarnings('ignore')\nsns.set_style('whitegrid')\nnp.random.seed(42)\n```\n:::\n\n\n## 1. Datos y modelos base\n\n::: {#3 .cell execution_count=2}\n``` {.python .cell-code}\ndf = pd.read_csv('../data/agresti_crab_satellites_dataset.csv')\nmean_W = df['W'].mean()\nstd_W  = df['W'].std()\ndf['W_scaled'] = (df['W'] - mean_W) / std_W\ny_obs = df['Sa'].values\n\nstan_data = {\n    'N': len(df),\n    'x': df['W_scaled'].values.tolist(),\n    'y': y_obs.tolist(),\n}\n\n# Cargar modelos base para comparación LOO final\nidata_pois = az.from_netcdf('../outputs/pois_idata.nc')\nidata_nb   = az.from_netcdf('../outputs/neg_idata.nc')\n# plot_ppc requiere nombre consistente entre observed_data y posterior_predictive\nidata_pois.posterior_predictive = idata_pois.posterior_predictive.rename({'y_rep': 'y'})\nidata_nb.posterior_predictive   = idata_nb.posterior_predictive.rename({'y_rep': 'y'})\n\nprint(f\"N observaciones: {len(df)}\")\nprint(f\"prop. ceros: {np.mean(y_obs == 0):.3f}\")\nprint(f\"índice de dispersión: {np.var(y_obs)/np.mean(y_obs):.3f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nN observaciones: 173\nprop. ceros: 0.358\níndice de dispersión: 3.376\n```\n:::\n:::\n\n\n## 2. Ajuste de ZIP y ZINB\n\nAmbos modelos tienen dos componentes con predictor lineal sobre `W_scaled`:\n- **Componente de conteo**: liga log, igual que los modelos base\n- **Componente de ceros**: liga logit, modela P(cero estructural | W)\n\nEl prior de `phi` en ZINB es `exponential(1)` — apropiado para un parámetro positivo\ncon media 1 y soporte (0, ∞).\n\n::: {#5 .cell execution_count=3}\n``` {.python .cell-code}\nimport os\n\nif os.path.exists('../outputs/zip_idata.nc') and os.path.exists('../outputs/zinb_idata.nc'):\n    print(\"Cargando .nc existentes...\")\n    idata_zip  = az.from_netcdf('../outputs/zip_idata.nc')\n    idata_zinb = az.from_netcdf('../outputs/zinb_idata.nc')\nelse:\n    print(\"Ajustando modelos...\")\n    zip_model  = cmdstanpy.CmdStanModel(stan_file='../models/zip_model.stan')\n    zinb_model = cmdstanpy.CmdStanModel(stan_file='../models/zinb_model.stan')\n\n    zip_fit = zip_model.sample(\n        data=stan_data, chains=4, iter_warmup=1000, iter_sampling=1000,\n        show_progress=True,\n    )\n    zinb_fit = zinb_model.sample(\n        data=stan_data, chains=4, iter_warmup=1000, iter_sampling=1000,\n        show_progress=True,\n    )\n\n    idata_zip = az.from_cmdstanpy(\n        posterior=zip_fit,\n        posterior_predictive='y_rep',\n        log_likelihood='log_lik',\n        observed_data={'y': y_obs},\n    )\n    idata_zinb = az.from_cmdstanpy(\n        posterior=zinb_fit,\n        posterior_predictive='y_rep',\n        log_likelihood='log_lik',\n        observed_data={'y': y_obs},\n    )\n    idata_zip.to_netcdf('../outputs/zip_idata.nc')\n    idata_zinb.to_netcdf('../outputs/zinb_idata.nc')\n\n# Renombrar para plot_ppc\nidata_zip.posterior_predictive  = idata_zip.posterior_predictive.rename({'y_rep': 'y'})\nidata_zinb.posterior_predictive = idata_zinb.posterior_predictive.rename({'y_rep': 'y'})\n\nprint(\"ZIP  grupos:\", list(idata_zip.groups()))\nprint(\"ZINB grupos:\", list(idata_zinb.groups()))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nCargando .nc existentes...\nZIP  grupos: ['posterior', 'posterior_predictive', 'log_likelihood', 'sample_stats', 'observed_data']\nZINB grupos: ['posterior', 'posterior_predictive', 'log_likelihood', 'sample_stats', 'observed_data']\n```\n:::\n:::\n\n\n## 3. Diagnósticos MCMC\n\n::: {#7 .cell execution_count=4}\n``` {.python .cell-code}\nprint(\"=== ZIP ===\")\ndisplay(az.summary(idata_zip,\n                   var_names=['alpha_count','beta_count','alpha_zero','beta_zero'],\n                   round_to=3))\n\nprint(\"\\n=== ZINB ===\")\ndisplay(az.summary(idata_zinb,\n                   var_names=['alpha_count','beta_count','phi','alpha_sm','alpha_zero','beta_zero'],\n                   round_to=3))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n=== ZIP ===\n```\n:::\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>mean</th>\n      <th>sd</th>\n      <th>hdi_3%</th>\n      <th>hdi_97%</th>\n      <th>mcse_mean</th>\n      <th>mcse_sd</th>\n      <th>ess_bulk</th>\n      <th>ess_tail</th>\n      <th>r_hat</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>alpha_count</th>\n      <td>1.477</td>\n      <td>0.050</td>\n      <td>1.383</td>\n      <td>1.566</td>\n      <td>0.001</td>\n      <td>0.001</td>\n      <td>3758.832</td>\n      <td>2803.684</td>\n      <td>1.001</td>\n    </tr>\n    <tr>\n      <th>beta_count</th>\n      <td>0.072</td>\n      <td>0.046</td>\n      <td>-0.013</td>\n      <td>0.159</td>\n      <td>0.001</td>\n      <td>0.001</td>\n      <td>3865.454</td>\n      <td>3305.843</td>\n      <td>1.002</td>\n    </tr>\n    <tr>\n      <th>alpha_zero</th>\n      <td>-0.788</td>\n      <td>0.190</td>\n      <td>-1.161</td>\n      <td>-0.443</td>\n      <td>0.003</td>\n      <td>0.003</td>\n      <td>3801.909</td>\n      <td>2859.664</td>\n      <td>1.001</td>\n    </tr>\n    <tr>\n      <th>beta_zero</th>\n      <td>-1.085</td>\n      <td>0.221</td>\n      <td>-1.543</td>\n      <td>-0.705</td>\n      <td>0.003</td>\n      <td>0.003</td>\n      <td>4045.371</td>\n      <td>3073.930</td>\n      <td>1.000</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n\n=== ZINB ===\n```\n:::\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>mean</th>\n      <th>sd</th>\n      <th>hdi_3%</th>\n      <th>hdi_97%</th>\n      <th>mcse_mean</th>\n      <th>mcse_sd</th>\n      <th>ess_bulk</th>\n      <th>ess_tail</th>\n      <th>r_hat</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>alpha_count</th>\n      <td>1.415</td>\n      <td>0.081</td>\n      <td>1.250</td>\n      <td>1.554</td>\n      <td>0.001</td>\n      <td>0.001</td>\n      <td>3109.943</td>\n      <td>2798.345</td>\n      <td>1.000</td>\n    </tr>\n    <tr>\n      <th>beta_count</th>\n      <td>0.098</td>\n      <td>0.074</td>\n      <td>-0.041</td>\n      <td>0.233</td>\n      <td>0.001</td>\n      <td>0.001</td>\n      <td>3637.571</td>\n      <td>2868.703</td>\n      <td>1.000</td>\n    </tr>\n    <tr>\n      <th>phi</th>\n      <td>3.509</td>\n      <td>1.010</td>\n      <td>1.824</td>\n      <td>5.475</td>\n      <td>0.019</td>\n      <td>0.019</td>\n      <td>2972.847</td>\n      <td>2724.716</td>\n      <td>1.002</td>\n    </tr>\n    <tr>\n      <th>alpha_sm</th>\n      <td>0.308</td>\n      <td>0.089</td>\n      <td>0.157</td>\n      <td>0.471</td>\n      <td>0.002</td>\n      <td>0.002</td>\n      <td>2972.847</td>\n      <td>2724.716</td>\n      <td>1.002</td>\n    </tr>\n    <tr>\n      <th>alpha_zero</th>\n      <td>-1.034</td>\n      <td>0.260</td>\n      <td>-1.523</td>\n      <td>-0.562</td>\n      <td>0.005</td>\n      <td>0.005</td>\n      <td>2948.451</td>\n      <td>2253.263</td>\n      <td>1.001</td>\n    </tr>\n    <tr>\n      <th>beta_zero</th>\n      <td>-1.183</td>\n      <td>0.270</td>\n      <td>-1.675</td>\n      <td>-0.676</td>\n      <td>0.005</td>\n      <td>0.005</td>\n      <td>3390.422</td>\n      <td>2351.002</td>\n      <td>1.002</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n::: {#8 .cell execution_count=5}\n``` {.python .cell-code}\nfig, axes = plt.subplots(4, 2, figsize=(12, 10))\naz.plot_trace(idata_zip,\n              var_names=['alpha_count','beta_count','alpha_zero','beta_zero'],\n              axes=axes, compact=False)\nfig.suptitle('Trace plots — ZIP', fontsize=13)\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](05_extended_models_files/figure-html/cell-6-output-1.png){width=1141 height=946}\n:::\n:::\n\n\n::: {#9 .cell execution_count=6}\n``` {.python .cell-code}\nfig, axes = plt.subplots(5, 2, figsize=(12, 12))\naz.plot_trace(idata_zinb,\n              var_names=['alpha_count','beta_count','phi','alpha_zero','beta_zero'],\n              axes=axes, compact=False)\nfig.suptitle('Trace plots — ZINB', fontsize=13)\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](05_extended_models_files/figure-html/cell-7-output-1.png){width=1140 height=1134}\n:::\n:::\n\n\n## 4. PPCs visuales — Distribución marginal\n\nComparamos los cuatro modelos lado a lado para ver visualmente la mejora en la\ncaptura de la distribución marginal de satélites.\n\n::: {#11 .cell execution_count=7}\n``` {.python .cell-code}\nfig, axes = plt.subplots(2, 2, figsize=(14, 8))\n\nfor ax, (idata, title) in zip(axes.flat, [\n    (idata_pois, 'Poisson'),\n    (idata_nb,   'Binomial Negativa'),\n    (idata_zip,  'ZIP'),\n    (idata_zinb, 'ZINB'),\n]):\n    az.plot_ppc(idata, ax=ax, num_pp_samples=100)\n    ax.set_title(title)\n    ax.set_xlabel('Número de satélites')\n    ax.set_xlim(-0.5, 17)\n\nplt.suptitle('PPC: Distribución marginal — cuatro modelos', fontsize=13)\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](05_extended_models_files/figure-html/cell-8-output-1.png){width=1333 height=758}\n:::\n:::\n\n\n## 5. PPCs con estadísticos de prueba\n\nEvaluamos la mejora con los mismos cuatro estadísticos del análisis base.\n\n::: {#13 .cell execution_count=8}\n``` {.python .cell-code}\ndef dispersion_index(y): return np.var(y) / np.mean(y)\ndef prop_zeros(y): return np.mean(y == 0)\n\ntest_stats = {\n    'std':               np.std,\n    'Índice dispersión': dispersion_index,\n    'max':               np.max,\n    'prop. ceros':       prop_zeros,\n}\n\nmodels = [\n    ('Poisson', idata_pois),\n    ('NegBin',  idata_nb),\n    ('ZIP',     idata_zip),\n    ('ZINB',    idata_zinb),\n]\n\ny_rep_dict = {}\nfor name, idata in models:\n    arr = idata.posterior_predictive['y'].values\n    y_rep_dict[name] = arr.reshape(-1, len(y_obs))\n\n# Tabla comparativa\nrows = []\nfor stat_name, stat_fn in test_stats.items():\n    t_obs = stat_fn(y_obs)\n    for name, y_rep_flat in y_rep_dict.items():\n        t_rep = np.array([stat_fn(y_rep_flat[s]) for s in range(y_rep_flat.shape[0])])\n        rows.append({\n            'Modelo': name,\n            'Estadístico': stat_name,\n            'T(y_obs)': round(t_obs, 3),\n            'E[T(y_rep)]': round(float(np.mean(t_rep)), 3),\n            'Bayesian p-value': round(float(np.mean(t_rep >= t_obs)), 3),\n        })\n\nsummary_df = pd.DataFrame(rows).sort_values(['Estadístico', 'Modelo'])\ndisplay(summary_df)\n```\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>Modelo</th>\n      <th>Estadístico</th>\n      <th>T(y_obs)</th>\n      <th>E[T(y_rep)]</th>\n      <th>Bayesian p-value</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>9</th>\n      <td>NegBin</td>\n      <td>max</td>\n      <td>15.000</td>\n      <td>27.266</td>\n      <td>0.963</td>\n    </tr>\n    <tr>\n      <th>8</th>\n      <td>Poisson</td>\n      <td>max</td>\n      <td>15.000</td>\n      <td>11.078</td>\n      <td>0.075</td>\n    </tr>\n    <tr>\n      <th>11</th>\n      <td>ZINB</td>\n      <td>max</td>\n      <td>15.000</td>\n      <td>16.025</td>\n      <td>0.624</td>\n    </tr>\n    <tr>\n      <th>10</th>\n      <td>ZIP</td>\n      <td>max</td>\n      <td>15.000</td>\n      <td>10.852</td>\n      <td>0.014</td>\n    </tr>\n    <tr>\n      <th>13</th>\n      <td>NegBin</td>\n      <td>prop. ceros</td>\n      <td>0.358</td>\n      <td>0.291</td>\n      <td>0.092</td>\n    </tr>\n    <tr>\n      <th>12</th>\n      <td>Poisson</td>\n      <td>prop. ceros</td>\n      <td>0.358</td>\n      <td>0.082</td>\n      <td>0.000</td>\n    </tr>\n    <tr>\n      <th>15</th>\n      <td>ZINB</td>\n      <td>prop. ceros</td>\n      <td>0.358</td>\n      <td>0.359</td>\n      <td>0.532</td>\n    </tr>\n    <tr>\n      <th>14</th>\n      <td>ZIP</td>\n      <td>prop. ceros</td>\n      <td>0.358</td>\n      <td>0.358</td>\n      <td>0.514</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>NegBin</td>\n      <td>std</td>\n      <td>3.139</td>\n      <td>4.089</td>\n      <td>0.889</td>\n    </tr>\n    <tr>\n      <th>0</th>\n      <td>Poisson</td>\n      <td>std</td>\n      <td>3.139</td>\n      <td>2.031</td>\n      <td>0.000</td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td>ZINB</td>\n      <td>std</td>\n      <td>3.139</td>\n      <td>3.282</td>\n      <td>0.635</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>ZIP</td>\n      <td>std</td>\n      <td>3.139</td>\n      <td>2.745</td>\n      <td>0.011</td>\n    </tr>\n    <tr>\n      <th>5</th>\n      <td>NegBin</td>\n      <td>Índice dispersión</td>\n      <td>3.376</td>\n      <td>5.709</td>\n      <td>0.950</td>\n    </tr>\n    <tr>\n      <th>4</th>\n      <td>Poisson</td>\n      <td>Índice dispersión</td>\n      <td>3.376</td>\n      <td>1.423</td>\n      <td>0.000</td>\n    </tr>\n    <tr>\n      <th>7</th>\n      <td>ZINB</td>\n      <td>Índice dispersión</td>\n      <td>3.376</td>\n      <td>3.695</td>\n      <td>0.691</td>\n    </tr>\n    <tr>\n      <th>6</th>\n      <td>ZIP</td>\n      <td>Índice dispersión</td>\n      <td>3.376</td>\n      <td>2.596</td>\n      <td>0.008</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n::: {#14 .cell execution_count=9}\n``` {.python .cell-code}\nfig, axes = plt.subplots(len(test_stats), len(models), figsize=(16, 4 * len(test_stats)))\n\nfor row, (stat_name, stat_fn) in enumerate(test_stats.items()):\n    t_obs = stat_fn(y_obs)\n    for col, (model_name, y_rep_flat) in enumerate(\n        (n, y_rep_dict[n]) for n, _ in models\n    ):\n        t_rep = np.array([stat_fn(y_rep_flat[s]) for s in range(y_rep_flat.shape[0])])\n        p_val = np.mean(t_rep >= t_obs)\n\n        ax = axes[row, col]\n        ax.hist(t_rep, bins=40, color='steelblue', alpha=0.7, label='T(y_rep)')\n        ax.axvline(t_obs, color='red', lw=2, label=f'T(y_obs)={t_obs:.2f}')\n        ax.set_title(f'{model_name} — {stat_name}\\np = {p_val:.3f}', fontsize=9)\n        ax.legend(fontsize=7)\n\nplt.suptitle('PPCs con estadísticos de prueba — cuatro modelos', fontsize=13, y=1.01)\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](05_extended_models_files/figure-html/cell-10-output-1.png){width=1526 height=1556}\n:::\n:::\n\n\n## 6. Comparación global LOO-CV — cuatro modelos\n\nELPD (Expected Log Predictive Density) — más alto = mejor capacidad predictiva out-of-sample.\n\n::: {#16 .cell execution_count=10}\n``` {.python .cell-code}\ncomparison = az.compare({\n    'Poisson': idata_pois,\n    'NegBin':  idata_nb,\n    'ZIP':     idata_zip,\n    'ZINB':    idata_zinb,\n})\ndisplay(comparison)\n\nax = az.plot_compare(comparison, figsize=(9, 3))\nax.set_title('Comparación LOO-CV — cuatro modelos')\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>rank</th>\n      <th>elpd_loo</th>\n      <th>p_loo</th>\n      <th>elpd_diff</th>\n      <th>weight</th>\n      <th>se</th>\n      <th>dse</th>\n      <th>warning</th>\n      <th>scale</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>ZINB</th>\n      <td>0</td>\n      <td>-358.487671</td>\n      <td>4.271028</td>\n      <td>0.000000</td>\n      <td>0.463509</td>\n      <td>14.449078</td>\n      <td>0.000000</td>\n      <td>False</td>\n      <td>log</td>\n    </tr>\n    <tr>\n      <th>ZIP</th>\n      <td>1</td>\n      <td>-369.544010</td>\n      <td>5.290222</td>\n      <td>11.056340</td>\n      <td>0.406980</td>\n      <td>18.528866</td>\n      <td>7.344846</td>\n      <td>False</td>\n      <td>log</td>\n    </tr>\n    <tr>\n      <th>NegBin</th>\n      <td>2</td>\n      <td>-378.435266</td>\n      <td>2.593778</td>\n      <td>19.947596</td>\n      <td>0.129511</td>\n      <td>13.521200</td>\n      <td>5.559237</td>\n      <td>False</td>\n      <td>log</td>\n    </tr>\n    <tr>\n      <th>Poisson</th>\n      <td>3</td>\n      <td>-465.237914</td>\n      <td>5.263937</td>\n      <td>106.750243</td>\n      <td>0.000000</td>\n      <td>23.064273</td>\n      <td>17.760474</td>\n      <td>False</td>\n      <td>log</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n\n::: {.cell-output .cell-output-display}\n![](05_extended_models_files/figure-html/cell-11-output-2.png){width=852 height=279}\n:::\n:::\n\n\n## 7. Posterior del componente de ceros\n\nEl componente logístico modela cómo varía P(cero estructural) con el ancho de la hembra.\n\n::: {#18 .cell execution_count=11}\n``` {.python .cell-code}\nW_range = np.linspace(df['W'].min(), df['W'].max(), 100)\nW_scaled_range = (W_range - mean_W) / std_W\n\nfig, axes = plt.subplots(1, 2, figsize=(13, 4))\n\nfor ax, (name, idata) in zip(axes, [('ZIP', idata_zip), ('ZINB', idata_zinb)]):\n    a0 = idata.posterior['alpha_zero'].values.flatten()\n    b0 = idata.posterior['beta_zero'].values.flatten()\n\n    # Curvas de theta para 200 muestras del posterior\n    idx = np.random.choice(len(a0), 200, replace=False)\n    for i in idx:\n        theta = 1 / (1 + np.exp(-(a0[i] + b0[i] * W_scaled_range)))\n        ax.plot(W_range, theta, color='steelblue', alpha=0.05)\n\n    # Curva media posterior\n    theta_mean = 1 / (1 + np.exp(-(a0.mean() + b0.mean() * W_scaled_range)))\n    ax.plot(W_range, theta_mean, color='navy', lw=2, label='Media posterior')\n\n    ax.set_xlabel('Ancho de caparazón W (cm)')\n    ax.set_ylabel('P(cero estructural | W)')\n    ax.set_title(f'{name} — Componente de ceros')\n    ax.legend()\n    ax.set_ylim(0, 1)\n\nplt.suptitle('Probabilidad de cero estructural vs ancho de caparazón', fontsize=12)\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](05_extended_models_files/figure-html/cell-12-output-1.png){width=1238 height=382}\n:::\n:::\n\n\n## 8. Conclusiones\n\n### Resultados de PPCs\n\n| Estadístico | y_obs | Poisson | NegBin | ZIP | ZINB |\n|---|---|---|---|---|---|\n| std | 3.14 | p=0.000 ❌ | p=0.892 ✅ | p=0.011 ⚠️ | p=0.635 ✅ |\n| Índice dispersión | 3.38 | p=0.000 ❌ | p=0.951 ✅ | p=0.008 ❌ | p=0.691 ✅ |\n| max | 15 | p=0.072 ⚠️ | p=0.963 ✅ | p=0.014 ⚠️ | p=0.624 ✅ |\n| **prop. ceros** | **0.358** | **p=0.000 ❌** | **p=0.092 ⚠️** | **p=0.514 ✅** | **p=0.532 ✅** |\n\n### Hallazgos principales\n\n**ZIP**: Resuelve el exceso de ceros (p=0.514) pero hereda la estructura de varianza de\nPoisson — falla en std (p=0.011) y en el índice de dispersión (p=0.008). En datos con\nambos problemas simultáneos, ZIP es una mejora parcial.\n\n**ZINB**: Captura simultáneamente inflación de ceros (p=0.532) y sobredispersión (p=0.691).\nEs el modelo más completo de los cuatro evaluados — supera a NegBin en prop. de ceros y\nmantiene su buen ajuste en dispersión.\n\n**Componente de ceros**: En ambos modelos ZI, `beta_zero < 0` — hembras con mayor ancho\nde caparazón tienen menor probabilidad de ser \"cero estructural\". Esto es interpretable:\nhembras más grandes atraen más satélites y es menos probable que no atraigan ninguno.\n\n**LOO-CV**: El ranking esperado es ZINB > ZIP > NegBin > Poisson. La diferencia\nZINB–NegBin cuantifica el valor de modelar explícitamente el proceso generador de ceros.\n\n### Limitación persistente\n\nEl predictor es únicamente el ancho de caparazón (W). Variables como condición de la\nespina (`S`) y color (`C`) no fueron incluidas. Una extensión natural es un ZINB con\nmúltiples predictores en ambos componentes.\n\n---\n\n## Extensiones y conexiones\n\n### Quasi-Poisson: la alternativa frecuentista\n\nEl enfoque bayesiano que recorrimos no es el único camino para manejar la\nsobredispersión en datos de conteo. Desde el paradigma frecuentista, el modelo\n**quasi-Poisson** (Wedderburn 1974) extiende la regresión Poisson relajando el\nsupuesto Var[Y] = E[Y] para permitir:\n\n$$\\text{Var}[Y_i] = \\phi \\cdot E[Y_i], \\quad \\phi > 1$$\n\ndonde $\\phi$ es un parámetro de dispersión estimado de los datos. El modelo trabaja\ncon una **función de cuasi-verosimilitud** (no requiere especificar una distribución\ncompleta para Y).\n\nEn R: `glm(y ~ x, family = quasipoisson)`. En Python, no existe una implementación\nnativa directa en `statsmodels`, lo que es en sí un argumento a favor de los modelos\ncon distribución explícita (NegBin, ZINB).\n\nEl análogo para datos de proporciones o tasas de conversión es el modelo\n**quasi-binomial** — misma idea, función de varianza $\\phi \\cdot p(1-p)$.\n\nLa limitación de los modelos quasi: no producen una distribución predictiva completa,\nlo que dificulta calcular intervalos de predicción calibrados o comparar modelos vía\nLOO-CV. El marco bayesiano con NegBin o ZINB provee todo esto de forma natural.\n\n",
    "supporting": [
      "05_extended_models_files/figure-html"
    ],
    "filters": [],
    "includes": {
      "include-in-header": [
        "<script src=\"https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js\" integrity=\"sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx\" crossorigin=\"anonymous\"></script>\n<script src=\"https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js\" integrity=\"sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2\" crossorigin=\"anonymous\" data-relocate-top=\"true\"></script>\n<script type=\"application/javascript\">define('jquery', [],function() {return window.jQuery;})</script>\n"
      ]
    }
  }
}